/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

function sum(a: number, b: number): number
/** The logging level. See the rust (log crate)[https://docs.rs/log] for more information. */
Trace = 'Trace',
Debug = 'Debug',
Info = 'Info',
Warn = 'Warn',
Error = 'Error',
Off = 'Off'
/** Set the logging level. */
function setLogLevel(level: LogLevel): void
/** Initialize the global metrics collection. */
function startMetricsCollection(): void
/**
 * Helper function that translates a key that was derived from the [`path_to_key`] function back
 * into a path.
 *
 * If `prefix` exists, it will be stripped before converting back to a path
 * If `root` exists, will add the root as a parent to the created path
 * Removes any null byte that has been appened to the key
 */
function keyToPath(key: Array<number>, prefix?: string | undefined | null, root?: string | undefined | null): string
/**
 * Helper function that creates a document key from a canonicalized path, removing the `root` and adding the `prefix`, if they exist
 *
 * Appends the null byte to the end of the key.
 */
function pathToKey(path: string, prefix?: string | undefined | null, root?: string | undefined | null): Array<number>
