
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    // Dokka generates the HTML API reference (self-hosted on GitHub Pages).
    alias(libs.plugins.dokka)

    // Publishes computer.iroh:iroh to Maven Central via Sonatype Central Portal.
    // Credentials/signing come from env vars in CI (see release.yml).
    alias(libs.plugins.maven.publish)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("net.java.dev.jna:jna:5.15.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    compilerOptions {
        optIn.add("kotlin.ExperimentalUnsignedTypes")
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    systemProperty("java.library.path", "lib/src/main/resources")
    systemProperty("jna.library.path", "lib/src/main/resources")

    testLogging {
        events("passed", "skipped", "failed")
    }
}

// Single source of truth for the Kotlin artifact version — `cargo make
// prepare-release <V>` rewrites the coordinates literal alongside Cargo.toml,
// iroh-js/package.json, and Package.swift.
mavenPublishing {
    // Vanniktech 0.34: Central Portal is the default; no SonatypeHost arg.
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()
    coordinates("computer.iroh", "iroh", "1.1.0")
    pom {
        name = "iroh"
        description = "Kotlin bindings for iroh: distributed systems made simple."
        url = "https://github.com/n0-computer/iroh-ffi"
        licenses {
            license {
                name = "MIT"
                url = "https://opensource.org/license/mit"
            }
            license {
                name = "Apache-2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0"
            }
        }
        developers {
            developer {
                id = "n0-computer"
                name = "n0"
                url = "https://www.iroh.computer"
            }
        }
        scm {
            url = "https://github.com/n0-computer/iroh-ffi"
            connection = "scm:git:git://github.com/n0-computer/iroh-ffi.git"
            developerConnection = "scm:git:ssh://git@github.com/n0-computer/iroh-ffi.git"
        }
    }
}
